version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:?No db password set}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - db-data:/var/lib/postgresql/data

  redis-cache:
    image: redis:6.2-alpine
    healthcheck: { test: ["CMD","redis-cli","ping"], interval: 5s, timeout: 3s, retries: 15 }

  redis-queue:
    image: redis:6.2-alpine
    healthcheck: { test: ["CMD","redis-cli","ping"], interval: 5s, timeout: 3s, retries: 15 }
    volumes: [ "redis-queue-data:/data" ]

  redis-socketio:
    image: redis:6.2-alpine
    healthcheck: { test: ["CMD","redis-cli","ping"], interval: 5s, timeout: 3s, retries: 15 }

  configurator:
    image: "frappe/frappe:${FRAPPE_VERSION}"
    entrypoint: ["bash","-lc"]
    command: |
      set -euo pipefail
      if [ -n "$$DB_PASSWORD" ]; then
        printf '%s:%s:*:%s:%s\n' "$$DB_HOST" "$$DB_PORT" "$$POSTGRES_USER" "$$DB_PASSWORD" > "$$HOME/.pgpass"
        chmod 600 "$$HOME/.pgpass"
      fi
      bench set-config -g db_type postgres
      bench set-config -g db_host "$$DB_HOST"
      bench set-config -gp db_port "$$DB_PORT"
      bench set-config -g redis_cache "redis://$${REDIS_CACHE:-redis-cache:6379}"
      bench set-config -g redis_queue "redis://$${REDIS_QUEUE:-redis-queue:6379}"
      bench set-config -g redis_socketio "redis://$${REDIS_SOCKETIO:-redis-socketio:6379}"
      bench set-config -gp socketio_port "$${SOCKETIO_PORT:-9000}"
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_PASSWORD: ${DB_PASSWORD:?No db password set}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  site-creator:
    image: "frappe/frappe:${FRAPPE_VERSION}"
    entrypoint: ["bash","-lc"]
    command: |
      set -euo pipefail
      if [ ! -d "sites/$$SITE_NAME" ]; then
        bench new-site "$$SITE_NAME" \
          --no-mariadb-socket \
          --db-type postgres \
          --db-host "$$DB_HOST" --db-port "$$DB_PORT" \
          --db-root-username "$$POSTGRES_USER" --db-root-password "$$DB_PASSWORD" \
          --admin-password "$$ADMIN_PASSWORD"
      fi
    environment:
      SITE_NAME: ${SITE_NAME:?Set SITE_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:?Set ADMIN_PASSWORD}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_PASSWORD: ${DB_PASSWORD:?No db password set}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    depends_on:
      db: { condition: service_healthy }
      configurator: { condition: service_completed_successfully }
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  backend:
    image: "frappe/frappe:${FRAPPE_VERSION}"
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_PASSWORD: ${DB_PASSWORD:?No db password set}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    command: ["bash","-lc","bench serve --port 8000 --noreload"]
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  websocket:
    image: "frappe/frappe:${FRAPPE_VERSION}"
    command: ["node","/home/frappe/frappe-bench/apps/frappe/socketio.js"]
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  queue-short:
    image: "frappe/frappe:${FRAPPE_VERSION}"
    command: ["bench","worker","--queue","short,default"]
    volumes: [ "sites:/home/frappe/frappe-bench/sites" ]

  queue-long:
    image: "frappe/frappe:${FRAPPE_VERSION}"
    command: ["bench","worker","--queue","long,default,short"]
    volumes: [ "sites:/home/frappe/frappe-bench/sites" ]

  scheduler:
    image: "frappe/frappe:${FRAPPE_VERSION}"
    command: ["bench","schedule"]
    volumes: [ "sites:/home/frappe/frappe-bench/sites" ]

  frontend:
    image: "frappe/erpnext-nginx:${FRAPPE_VERSION}"
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: ${FRAPPE_SITE_NAME_HEADER:-$$host}
      PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-120}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-50m}
    depends_on:
      - backend
      - websocket
    ports:
      - "${HTTP_PUBLISH_PORT:-8080}:8080"
    volumes:
      - sites:/var/www/html/sites

volumes:
  sites:
  db-data:
  redis-queue-data:
